reservoir:
  trigger: 20
  echo:    21
  min_level:  15.8
  min_volume:  2.0
  max_level:   3.2
  max_volume: 11.0
  levels:
  - [ 3.2, 11.0]
  - [ 4.5, 10.0]
  - [ 5.7,  9.0]
  - [ 7.4,  8.0]
  - [ 9.0,  7.0]
  - [10.5,  6.0]
  - [11.7,  5.0]
  - [12.9,  4.0]
  - [14.2,  3.0]
  - [15.8,  2.0]

reservoir2:
  pins:
    trigger: 20
    echo:    21
  levels:
    min: 15.8
    max:  3.2

planter:
  trigger: 23
  echo:    24
  min_level: 12.5
  max_level:  3.5
  low_level:  6.0

pump:
  switch: 5

log:
  fill-events: /home/pi/water-log.csv
  levels:      /home/pi/levels.csv
