reservoir:
  trigger: 20
  echo:    21
  min_level:  29.7
  min_volume:  4.0
  max_level:   8.8
  max_volume: 24.0

planter:
  trigger: 23
  echo:    24
  min_level: 12.5
  max_level:  4.0
  low_level:  7.0
  range_max: 14.0
  range_min:  3.0

pump:
  switch: 5

log:
  fill-events: /home/pi/water-log.csv
  levels:      /home/pi/levels.csv
